name: Add Rules to Cloudflare Gateway
on:
  schedule:
    - cron: "10 20 * * *"
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  run:
    name: Cloudflare Gateway
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # - name: Install Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: 3.11

      # - name: Install Dependencies
      #   run: pip install -r requirements.txt

      - name: Compile go
        uses: actions/setup-go@v4
        with:
          go-version: "stable"
          check-latest: true
      - name: Build
        run: go build
      - name: Run
        run: ./cloudflare_pihole
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_IDENTIFIER: ${{ secrets.CF_IDENTIFIER }}
          PYTHONDONTWRITEBYTECODE: 1

      # - name: Cloudflare Gateway Zero Trust
      #   run: python main.py
      # env:
      #   CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      #   CF_IDENTIFIER: ${{ secrets.CF_IDENTIFIER }}
      #   PYTHONDONTWRITEBYTECODE: 1
